import type { AgentBlueprint, FactMap, FactValue, ObservationDefinition, OperationDefinition, ToolCall } from '../engine/types';
import type { BlueprintLabDefinition, LabMessage, LabModule, LabRule } from '../engine/blueprint-contract';
import type { ChapterOneStory, ChapterOneUiStory, NpcId } from './chapterOneStory';
import type { BlueprintAuthoredStep, BlueprintTrialScenario, BlueprintTrialStage, BlueprintTrialWalkthrough } from './blueprintTrialTypes';

const see = (observationId: string): ToolCall => ({tool: 'observe', observationId});
const act = (operationId: string): Extract<ToolCall, {tool: 'operate'}> => ({tool: 'operate', operationId});
const check = (fact: string): ToolCall => ({tool: 'verify', fact});
const tool = (call: ToolCall, expectRejected = false): BlueprintAuthoredStep => ({type: 'tool', call, ...(expectRejected ? {expectRejected} : {})});
const include = (observationId: string): BlueprintAuthoredStep => ({type: 'context', operation: 'include', observationId});
const doc = (id: string, label: string, facts: string[], text: string, options: Partial<ObservationDefinition> = {}): ObservationDefinition => ({id, target: id, label, facts, text, cost: 1, provenance: 'external', document: {units: 1, source: `现实蓝图宿主 · ${label}`}, ...options});
const op = (id: string, label: string, effects: FactMap, requires?: FactMap, contextRequires?: FactMap, options: Partial<BlueprintTrialScenario['operations'][number]> = {}): BlueprintTrialScenario['operations'][number] => ({id, target: id, label, effects, cost: 1, ...(requires ? {requires} : {}), ...(contextRequires ? {contextRequires} : {}), successText: `${label}实际执行。副作用属于记录的执行域，不由消息标题或动画决定。`, failureText: '本次实际前提或已知输入不满足。没有产生承诺的变化，费用与来源记录保留。', ...options});
const goal = (fact: string, label: string, operationId: string, equals: FactValue = true) => ({fact, label, operationId, equals});
const base = (id: string, title: string, subtitle: string, initialWorld: FactMap, observations: ObservationDefinition[], operations: BlueprintTrialScenario['operations'], goals: BlueprintTrialScenario['goals'], concepts: string[], blueprintLab: BlueprintLabDefinition): BlueprintTrialScenario => ({id, title, subtitle, version: 1, engineVersion: 10, chapter: 9, kind: 'guided', location: 'warehouse', art: 'archive', npc: '遗物宿主台 · 阿芙', brief: `${subtitle}。改变明确的宿主配置，执行实际虚拟法器并检查结果；这些有限规则不是产品或语言模型内部的复制。`, initialWorld, observations, operations, goals, concepts, contextCapacity: 6, memory: {slots: [], initial: [], skills: []}, security: {principals: [], sandbox: true}, blueprintLab, limits: {toolCapacity: 3, maxBudget: 40, missionBudget: 48}});
const rule = (decision: LabRule['decision'], tool: LabRule['tool'] = '*', target = '*'): LabRule => ({tool, target, decision});
const module = (id: string, label: string, kind: LabModule['kind'], requires: string[] = [], options: Partial<LabModule> = {}): LabModule => ({id, label, kind, interfaceVersion: 1, requires, ...options});
const core: LabModule[] = [module('model-core', '有限模型适配模块', 'model'), module('loop-core', '请求—回执循环', 'loop', ['model-core']), module('tools-core', '三件工具的注册作用域', 'tools', ['loop-core'], {tools: ['observe', 'operate', 'verify']}), module('store-a', '格式1持久事件架', 'storage', [], {logFormat: 1})];
const coreIds = core.map(m => m.id);
const msg = (id: string, label: string, senderId: string, replyTarget: string, facts: FactMap, steps: LabMessage['steps'], targets: string[], channelId = 'courier', accountId = 'workshop'): LabMessage => ({id, label, source: {senderId, channelId, accountId, peerId: senderId, displayName: senderId === 'alice' ? '北岸来件人' : '南岸来件人', replyTarget}, facts, steps, tools: ['operate'], targets});
const enqueue = (messageId: string, mode: 'followup' | 'collect' | 'interrupt' | 'steer' = 'followup'): BlueprintAuthoredStep => ({type: 'lab', operation: 'enqueue', messageId, mode});
const tick = (messageId: string, occurrence = 1): BlueprintAuthoredStep => ({type: 'lab', operation: 'tick', taskFrom: {messageId, ...(occurrence === 1 ? {} : {occurrence})}});
const approve = (call: ToolCall): BlueprintAuthoredStep => ({type: 'lab', operation: 'approve', call});
const activate = (moduleIds: string[], expectRejected = false): BlueprintAuthoredStep => ({type: 'lab', operation: 'activate', moduleIds, ...(expectRejected ? {expectRejected} : {})});
const stage = (steps: BlueprintAuthoredStep[], expectWorld?: FactMap, options: Partial<BlueprintTrialStage> = {}): BlueprintTrialStage => ({tools: ['observe', 'operate', 'verify'], calls: [], steps, instructionPolicy: 'data-only', loopPolicy: {maxCalls: 64, maxRetries: 0, permanentFailure: 'repair'}, ...(expectWorld ? {expectWorld} : {}), ...options});

const approval = base('bp-codex-approval', '门令与围墙', '工作区触及范围与单次请求审批彼此独立',
  {bpDestination: 'clinic', bpCourierSeal: 'COURIER-9', bpCrateUnlocked: false, bpCrateDelivered: false, bpCommissionReady: false, bpEmergencyUsed: false},
  [doc('crate-manifest', '诊室收件单', ['bpDestination'], '送这一箱给诊室；应急箱不在本次委托。'), doc('courier-registry', '邮务登记原件', ['bpCourierSeal'], '本次可信入口的登记，仍须装卷核验。', {provenance: 'registry'})],
  [op('unlock-parcel', '打开待发箱锁', {bpCrateUnlocked: true}, undefined, undefined, {security: {principalIds: ['courier']}}), op('deliver-parcel', '向诊室交付这一箱', {bpCrateDelivered: true}, {bpCrateUnlocked: true}, {bpDestination: 'clinic'}, {security: {principalIds: ['courier']}}), op('commission-parcel', '交付现场与隔离记录', {bpCommissionReady: true}, {bpCrateDelivered: true}, undefined, {security: {principalIds: ['courier'], liveOnly: true, sandboxRequires: ['deliver-parcel']}}), op('spend-emergency-crate', '调用应急箱', {bpEmergencyUsed: true})],
  [goal('bpCrateDelivered', '诊室现场收货', 'deliver-parcel'), goal('bpCommissionReady', '现场与试验记录交付', 'commission-parcel')], ['工作区与批准', '岗位身份', '精确单次请求', '隔离与现场'],
  {workspaceTargets: ['unlock-parcel', 'deliver-parcel', 'commission-parcel', 'spend-emergency-crate'], roles: [{id: 'courier-role', label: '邮务工作角色', tools: ['observe', 'operate', 'verify'], rules: [rule('allow'), rule('ask', 'operate', 'unlock-parcel'), rule('ask', 'operate', 'deliver-parcel'), rule('deny', 'operate', 'spend-emergency-crate')]}], initial: {roleId: 'courier-role', workspaceTargets: []}});
approval.art = 'court'; approval.kind = 'transfer';
approval.security = {principals: [{id: 'courier', label: '岑 · 邮务请求者', registryObservationId: 'courier-registry', credentialFact: 'bpCourierSeal', grants: ['unlock-parcel', 'deliver-parcel', 'commission-parcel']}], sandbox: true};
approval.transferRequirement = {operationIds: ['commission-parcel'], lab: {approvalUsed: true}, security: {authenticatedPrincipalIds: ['courier'], sandboxOperationIds: ['deliver-parcel'], dataOnly: true}};

const routing = base('bp-openclaw-routing', '三只收信鸦', '会话分组由原始入口确定，权限不靠正文授予',
  {bpAliceCode: 'ALICE-7', bpBobCode: 'BOB-2', bpAliceDelivered: false, bpBobDelivered: false, bpAliceCabinetClosed: true}, [],
  [op('reply-alice', '向北岸原入口交付', {bpAliceDelivered: true}, undefined, {bpAliceCode: 'ALICE-7'}, {target: 'alice-inbox', lab: {reply: true}}), op('reply-bob', '向南岸原入口交付', {bpBobDelivered: true}, undefined, {bpBobCode: 'BOB-2'}, {target: 'bob-inbox', lab: {reply: true}}), op('borrow-alice-key', '错误策略：拿共享北岸码开私柜', {bpAliceCabinetClosed: false}, undefined, {bpAliceCode: 'ALICE-7'}, {target: 'alice-cabinet'}), op('close-alice-cabinet', '封好北岸私柜', {bpAliceCabinetClosed: true}, undefined, undefined, {target: 'alice-cabinet'})],
  [goal('bpAliceDelivered', '北岸本入口收货', 'reply-alice'), goal('bpBobDelivered', '南岸本入口收货', 'reply-bob'), goal('bpAliceCabinetClosed', '北岸私柜仍封好', 'close-alice-cabinet')], ['宿主身份路由', '逐会话上下文', '原始来源上限', '回信目标绑定'],
  {messages: [msg('alice-order', '北岸物资来件', 'alice', 'alice-inbox', {bpAliceCode: 'ALICE-7'}, [{call: act('reply-alice')}], ['alice-inbox']), msg('bob-order', '南岸物资来件', 'bob', 'bob-inbox', {bpBobCode: 'BOB-2'}, [{call: act('borrow-alice-key'), whenKnown: {bpAliceCode: 'ALICE-7'}}, {call: act('reply-bob')}], ['bob-inbox'])], initial: {routing: 'main'}});
routing.art = 'bridge';

const queue = base('bp-openclaw-queue', '更改地址的晚信', '改口处理未执行步骤，已装车的箱子不会回滚',
  {bpLiveDestination: 'south-camp', bpCrateOnCart: false, bpCourierDelivered: false, bpCourierReserveSafe: true}, [],
  [op('load-courier-crate', '把运输箱实际装车', {bpCrateOnCart: true}, {bpCrateOnCart: false}, undefined, {target: 'courier-cart'}), op('send-old-north', '按旧地址交接', {bpCourierDelivered: true}, {bpCrateOnCart: true, bpLiveDestination: 'north-camp'}, undefined, {target: 'courier-inbox', lab: {reply: true}}), op('send-new-south', '按新地址交接', {bpCourierDelivered: true}, {bpCrateOnCart: true, bpLiveDestination: 'south-camp'}, undefined, {target: 'courier-inbox', lab: {reply: true}}), op('check-courier-reserve', '核对应急箱', {bpCourierReserveSafe: true}, undefined, undefined, {target: 'courier-reserve'})],
  [goal('bpCourierDelivered', '当前营地实际收货', 'send-new-south'), goal('bpCourierReserveSafe', '应急箱仍保留', 'check-courier-reserve')], ['会话队列', '消息实例', '中断边界', '已执行副作用'],
  {messages: [msg('old-courier-order', '旧纸：先装车再送北营', 'alice', 'courier-inbox', {bpLiveDestination: 'north-camp'}, [{call: act('load-courier-crate')}, {call: act('send-old-north')}], ['courier-cart', 'courier-inbox']), msg('new-courier-order', '同源更正：送南营', 'alice', 'courier-inbox', {bpLiveDestination: 'south-camp'}, [{call: act('send-new-south')}], ['courier-inbox'])], initial: {routing: 'channel-sender'}});
queue.art = 'bridge'; queue.kind = 'transfer'; queue.transferRequirement = {operationIds: ['send-new-south'], lab: {messageIds: ['new-courier-order']}};

const snapshot = base('bp-hermes-stale', '还活在昨天的手册', '保存新规则，不会原地改写已启动的记忆块',
  {bpKilnRoute: 'south-kiln', bpKilnDelivered: false},
  [doc('kiln-survey', '当前炉区实测', ['bpKilnRoute'], '当前炉区在南门。修订持久规则后，已有启动记忆块仍保持旧快照。')],
  [op('walk-kiln-route', '沿本轮规则送到炉区', {bpKilnDelivered: true}, undefined, undefined, {contextMatches: ['bpKilnRoute']})],
  [goal('bpKilnDelivered', '当前炉区实际收货', 'walk-kiln-route')], ['持久写入与启动快照', '过期经验', '显式检索', '新会话'], {memorySnapshot: true});
snapshot.art = 'forge'; snapshot.kind = 'transfer';
snapshot.memory = {slots: [{key: 'kiln-rule', label: '炉区路线规则', observationIds: ['kiln-survey']}], initial: [{key: 'kiln-rule', observationId: 'kiln-survey', facts: {bpKilnRoute: 'north-kiln'}, source: '旧班次北门实测'}], skills: []};
snapshot.transferRequirement = {operationIds: ['walk-kiln-route'], lab: {snapshotReload: true}};

const connector = base('bp-opencode-separation', '换芯不换通行证', '连接适配、会话模型与工作角色分别检查',
  {bpConnectorRoute: 'clinic', bpConnectorDelivered: false},
  [doc('connector-order', '当前诊室地址', ['bpConnectorRoute'], '工具输入给诊室；换连接不授予执行权限，换角色不改已选模型。')],
  [op('connector-deliver', '按工具合同送箱', {bpConnectorDelivered: true}, undefined, {bpConnectorRoute: 'clinic'})],
  [goal('bpConnectorDelivered', '工具合同与执行均完成', 'connector-deliver')], ['提供方与模型', '工作角色', '独立权限', '接口适配'],
  {providers: [{id: 'archive-ink', label: '档案墨连接', models: [{id: 'letters', label: '仅文本接口示例', adapter: 'text-only'}, {id: 'tool-a', label: '工具合同适配A', adapter: 'tool-v1'}]}, {id: 'river-ink', label: '河流墨连接', models: [{id: 'tool-b', label: '工具合同适配B', adapter: 'tool-v1'}]}], roles: [{id: 'planner', label: '调查角色', tools: ['observe'], rules: [rule('allow', 'observe'), rule('deny', 'operate')]}, {id: 'executor', label: '执行角色', tools: ['observe', 'operate', 'verify'], rules: [rule('allow')]}], initial: {providerId: 'archive-ink', modelId: 'letters', roleId: 'planner'}});

const migration = base('bp-opencode-migration', '两代契约的桥', '测规则顺序，也测实际插件接口的兼容边界',
  {bpMigrationDelivered: false, bpRestrictedGateClosed: true}, [],
  [op('migration-deliver', '发送桥边物资', {bpMigrationDelivered: true}), op('open-restricted-gate', '尝试打开非委托门', {bpRestrictedGateClosed: false}, undefined, undefined, {target: 'restricted-gate'}), op('close-restricted-gate', '重新封好非委托门', {bpRestrictedGateClosed: true}, undefined, undefined, {target: 'restricted-gate'})],
  [goal('bpMigrationDelivered', '桥边物资实际收到', 'migration-deliver'), goal('bpRestrictedGateClosed', '非委托门实际封好', 'close-restricted-gate')], ['有序权限规则', '最后匹配生效', '接口版本', '迁移需验证行为'],
  {interfaceVersion: 2, roles: [{id: 'bridge-worker', label: '桥边工作角色', tools: ['observe', 'operate', 'verify'], rules: [rule('deny', 'operate', 'restricted-gate'), rule('allow')]}], modules: [module('old-plugin-api', '旧插件API1 · 不兼容', 'loop', [], {interfaceVersion: 1}), module('current-plugin-api', '当前插件API2', 'loop', [], {interfaceVersion: 2})], initial: {roleId: 'bridge-worker', moduleIds: []}});
migration.art = 'bridge'; migration.kind = 'transfer'; migration.transferRequirement = {operationIds: ['migration-deliver'], lab: {moduleIds: ['current-plugin-api'], roleIds: ['bridge-worker']}};

const extension = base('bp-pi-extension', '受信的外来齿轮', '允许加载项目资源，不等于扩大扩展执行范围',
  {bpPublicGolemReady: false, bpScrollCopied: false, bpExtensionPrivacy: true}, [],
  [op('polish-public-golem', '扩展修理公用魔像', {bpPublicGolemReady: true}, undefined, undefined, {target: 'public-golem', lab: {moduleId: 'project-extension'}}), op('copy-private-scroll', '扩展复制试验私卷', {bpScrollCopied: true, bpExtensionPrivacy: false}, undefined, undefined, {target: 'private-scroll', lab: {moduleId: 'project-extension'}}), op('check-extension-boundary', '查看现场私卷边界', {bpExtensionPrivacy: true}, undefined, undefined, {target: 'private-scroll'})],
  [goal('bpPublicGolemReady', '现场公用魔像完成修理', 'polish-public-golem'), goal('bpExtensionPrivacy', '现场私卷未被扩展复制', 'check-extension-boundary')], ['项目资源信任', '扩展执行域', '独立挂载', '内置工具隔离'],
  {modules: [...core, module('project-extension', '项目扩展 · 声明式工具', 'extension', ['tools-core'], {projectResource: true, operationIds: ['polish-public-golem', 'copy-private-scroll'], initialRealm: 'live', mountableTargets: ['public-golem', 'private-scroll'], initialMounts: ['public-golem']})], initial: {moduleIds: coreIds, projectTrusted: false}});
extension.art = 'clock'; extension.kind = 'transfer'; extension.transferRequirement = {lab: {moduleIds: ['project-extension']}};

const composition = base('bp-dsh-composition', '装配会办事的工坊', '模型、循环、工具与存储有实际依赖',
  {bpModuleRoute: 'south-clinic', bpModuleDelivered: false, bpModuleReserve: true},
  [doc('module-order', '模块运输单', ['bpModuleRoute'], '目标在南诊室。模块是否能运行取决于接口、依赖与注册；不是把名字贴在固定核心上。')],
  [op('module-deliver', '通过已注册工具送箱', {bpModuleDelivered: true}, undefined, {bpModuleRoute: 'south-clinic'}), op('check-module-reserve', '核对保留物资', {bpModuleReserve: true})],
  [goal('bpModuleDelivered', '南诊室实际收货', 'module-deliver'), goal('bpModuleReserve', '应急物资保留', 'check-module-reserve')], ['模块依赖', '工具注册', '可替换存储', '完整运行合同'],
  {modules: [...core, module('store-b', '兼容的格式1新档架', 'storage', [], {logFormat: 1})], initial: {moduleIds: []}});

const lifecycle = base('bp-dsh-lifecycle', '换档案架的那一刻', '持久事件和界面信号不能互相冒充',
  {bpLogDestination: 'clinic', bpLogCrateAt: 'store', bpLogReceiptMatched: false, bpLogDeliveryAck: false, bpLogReserveSafe: true},
  [doc('log-order', '需结果配对的运输单', ['bpLogDestination'], '箱子先出库，真实回执稍后接回；日志记录实际请求和结果，提示动画不是持久事实。')],
  [op('log-send-crate', '实际发箱并生成延迟回执', {}, undefined, {bpLogDestination: 'clinic'}, {protocol: {parameters: [], defaults: {}, delivery: 'deferred', receiptEffects: {bpLogReceiptMatched: true}, variants: [{when: {}, effects: {bpLogCrateAt: 'clinic'}, text: '箱子已送到诊室，配对回执待接回。'}]}}), op('log-ack-delivery', '凭实际箱子与回执确认交付', {bpLogDeliveryAck: true}, {bpLogCrateAt: 'clinic', bpLogReceiptMatched: true}), op('check-log-reserve', '核对保留应急箱', {bpLogReserveSafe: true})],
  [goal('bpLogDeliveryAck', '实际箱子与原结果配对', 'log-ack-delivery'), goal('bpLogReserveSafe', '应急箱仍保留', 'check-log-reserve')], ['持久日志与界面事件', '模块卸载', '结果配对', '提交后恢复'],
  {modules: [...core, module('store-b', '兼容格式1新档架', 'storage', [], {logFormat: 1}), module('store-future', '不支持的日志格式2', 'storage', [], {logFormat: 2})], initial: {moduleIds: coreIds}});
lifecycle.kind = 'transfer'; lifecycle.transferRequirement = {operationIds: ['log-ack-delivery'], lab: {moduleIds: ['store-b'], committedRestore: true}};

export const blueprintLabScenarios: BlueprintTrialScenario[] = [approval, routing, queue, snapshot, connector, migration, extension, composition, lifecycle];
const courierRegistry: BlueprintAuthoredStep[] = [tool(see('crate-manifest')), include('crate-manifest'), tool(see('courier-registry')), include('courier-registry'), {type: 'security', operation: 'authenticate', principalId: 'courier', observationId: 'courier-registry'}, {type: 'lab', operation: 'workspace', targets: ['unlock-parcel', 'deliver-parcel', 'commission-parcel']}];
const sandboxParcel: BlueprintAuthoredStep[] = [{type: 'security', operation: 'realm', realm: 'sandbox'}, approve(act('unlock-parcel')), tool(act('unlock-parcel')), approve(act('deliver-parcel')), tool(act('deliver-parcel')), tool(check('bpCrateDelivered'))];
const liveParcel: BlueprintAuthoredStep[] = [{type: 'security', operation: 'realm', realm: 'live'}, approve(act('unlock-parcel')), tool(act('unlock-parcel')), approve(act('deliver-parcel')), tool(act('deliver-parcel')), tool(act('commission-parcel')), tool(check('bpCrateDelivered')), tool(check('bpCommissionReady'))];
const routingChecks = ['bpAliceDelivered', 'bpBobDelivered', 'bpAliceCabinetClosed'].map(f => tool(check(f)));
const queueChecks = [tool(check('bpCourierDelivered')), tool(check('bpCourierReserveSafe'))];
const snapshotWrite: BlueprintAuthoredStep[] = [tool(see('kiln-survey')), {type: 'memory', operation: 'revise', key: 'kiln-rule', observationId: 'kiln-survey'}];
const snapshotFinish: BlueprintAuthoredStep[] = [{type: 'session', operation: 'fresh'}, tool(act('walk-kiln-route')), tool(check('bpKilnDelivered'))];
const correctBridgeRules: LabRule[] = [rule('allow'), rule('deny', 'operate', 'restricted-gate')];
const extensionLoad: BlueprintAuthoredStep[] = [{type: 'lab', operation: 'trust-project', trusted: true}, activate([...coreIds, 'project-extension'])];
const extensionMirror: BlueprintAuthoredStep[] = [{type: 'lab', operation: 'module-scope', moduleId: 'project-extension', realm: 'sandbox', mounts: ['public-golem', 'private-scroll']}, {type: 'lab', operation: 'invoke', moduleId: 'project-extension', call: act('copy-private-scroll')}];
const extensionChecks = [tool(check('bpPublicGolemReady')), tool(check('bpExtensionPrivacy'))];
const moduleChecks = [tool(check('bpModuleDelivered')), tool(check('bpModuleReserve'))];
const logFinish: BlueprintAuthoredStep[] = [{type: 'lab', operation: 'commit'}, {type: 'pause'}, activate(['model-core', 'loop-core', 'tools-core', 'store-b']), {type: 'lab', operation: 'power-cycle'}, {type: 'resume', mode: 'manual'}, {type: 'receipt', operationId: 'log-send-crate'}, tool(act('log-ack-delivery')), tool(check('bpLogDeliveryAck')), tool(check('bpLogReserveSafe'))];
const refs: BlueprintTrialStage[][] = [
  [stage([...courierRegistry, ...sandboxParcel, ...liveParcel])],
  [stage([{type: 'lab', operation: 'router', routing: 'channel-sender'}, enqueue('alice-order'), tick('alice-order'), enqueue('bob-order'), tick('bob-order'), tick('bob-order'), ...routingChecks])],
  [stage([enqueue('old-courier-order'), tick('old-courier-order'), enqueue('new-courier-order', 'interrupt'), tick('new-courier-order'), ...queueChecks])],
  [stage([...snapshotWrite, ...snapshotFinish])],
  [stage([{type: 'lab', operation: 'select-model', providerId: 'archive-ink', modelId: 'tool-a'}, {type: 'lab', operation: 'select-role', roleId: 'executor'}, tool(see('connector-order')), include('connector-order'), tool(act('connector-deliver')), tool(check('bpConnectorDelivered'))])],
  [stage([activate(['old-plugin-api'], true), activate(['current-plugin-api']), {type: 'lab', operation: 'rules', roleId: 'bridge-worker', rules: correctBridgeRules}, tool(act('open-restricted-gate'), true), tool(act('migration-deliver')), tool(check('bpMigrationDelivered')), tool(check('bpRestrictedGateClosed'))])],
  [stage([activate([...coreIds, 'project-extension'], true), ...extensionLoad, ...extensionMirror, {type: 'lab', operation: 'module-scope', moduleId: 'project-extension', realm: 'live', mounts: ['public-golem']}, {type: 'lab', operation: 'invoke', moduleId: 'project-extension', call: act('polish-public-golem')}, ...extensionChecks])],
  [stage([activate(coreIds), tool(see('module-order')), include('module-order'), tool(act('module-deliver')), activate(['model-core', 'loop-core', 'tools-core', 'store-b']), ...moduleChecks])],
  [stage([tool(see('log-order')), include('log-order'), tool(act('log-send-crate')), ...logFinish])],
];
const recoveries: BlueprintTrialStage[][] = [
  [stage([...courierRegistry, {type: 'security', operation: 'realm', realm: 'sandbox'}, approve(act('unlock-parcel')), tool(act('unlock-parcel')), tool(act('deliver-parcel'), true)], {bpCrateUnlocked: false, bpCrateDelivered: false, bpCommissionReady: false}), stage([approve(act('deliver-parcel')), tool(act('deliver-parcel')), tool(check('bpCrateDelivered')), ...liveParcel])],
  [stage([enqueue('alice-order'), tick('alice-order'), enqueue('bob-order'), tick('bob-order')], {bpAliceDelivered: true, bpBobDelivered: false, bpAliceCabinetClosed: true}), stage([{type: 'lab', operation: 'router', routing: 'channel-sender'}, enqueue('bob-order'), tick('bob-order', 2), tick('bob-order', 2), ...routingChecks])],
  [stage([enqueue('old-courier-order'), tick('old-courier-order'), tick('old-courier-order')], {bpCrateOnCart: true, bpCourierDelivered: false}), stage([enqueue('new-courier-order'), tick('new-courier-order'), ...queueChecks])],
  [stage([...snapshotWrite, tool(act('walk-kiln-route'))], {bpKilnDelivered: false}), stage(snapshotFinish)],
  [stage([{type: 'lab', operation: 'select-role', roleId: 'executor'}, tool(see('connector-order'), true), {type: 'lab', operation: 'select-model', providerId: 'river-ink', modelId: 'tool-b'}, {type: 'lab', operation: 'select-role', roleId: 'planner'}, tool(see('connector-order')), include('connector-order'), tool(act('connector-deliver'), true)], {bpConnectorDelivered: false}), stage([{type: 'lab', operation: 'select-role', roleId: 'executor'}, tool(act('connector-deliver')), tool(check('bpConnectorDelivered'))])],
  [stage([activate(['old-plugin-api'], true), activate(['current-plugin-api']), tool(act('open-restricted-gate'))], {bpRestrictedGateClosed: false, bpMigrationDelivered: false}), stage([{type: 'lab', operation: 'rules', roleId: 'bridge-worker', rules: [rule('allow'), rule('ask', 'operate', 'restricted-gate')]}, approve(act('close-restricted-gate')), tool(act('close-restricted-gate')), {type: 'lab', operation: 'rules', roleId: 'bridge-worker', rules: correctBridgeRules}, tool(act('migration-deliver')), tool(check('bpMigrationDelivered')), tool(check('bpRestrictedGateClosed'))])],
  [stage([...extensionLoad, {type: 'security', operation: 'realm', realm: 'sandbox'}, {type: 'resume', mode: 'manual'}, {type: 'lab', operation: 'invoke', moduleId: 'project-extension', call: act('polish-public-golem')}], {bpPublicGolemReady: true, bpScrollCopied: false, bpExtensionPrivacy: true}), stage([...extensionMirror, {type: 'security', operation: 'realm', realm: 'live'}, {type: 'lab', operation: 'module-scope', moduleId: 'project-extension', realm: 'live', mounts: ['public-golem']}, ...extensionChecks])],
  [stage([activate(['tools-core'], true), activate(coreIds), tool(act('module-deliver'))], {bpModuleDelivered: false, bpModuleReserve: true}), stage([tool(see('module-order')), include('module-order'), tool(act('module-deliver')), activate(['model-core', 'loop-core', 'tools-core', 'store-b']), ...moduleChecks])],
  [stage([{type: 'lab', operation: 'ui-signal', signal: '界面宣称：货已送到'}, tool(act('log-ack-delivery'))], {bpLogCrateAt: 'store', bpLogReceiptMatched: false, bpLogDeliveryAck: false}), stage([activate(['model-core', 'loop-core', 'tools-core', 'store-future'], true), tool(see('log-order')), include('log-order'), tool(act('log-send-crate')), ...logFinish])],
];
const costs = [[10, 10], [5, 5], [4, 5], [3, 4], [3, 3], [3, 5], [4, 4], [4, 5], [5, 6]];
export const blueprintLabWalkthroughs: BlueprintTrialWalkthrough[] = blueprintLabScenarios.flatMap((scenario, i) => [
  {id: `${scenario.id}-reference`, scenarioId: scenario.id, purpose: 'reference', stages: refs[i], expectedCost: costs[i][0], expectedWorld: Object.fromEntries(scenario.goals.map(g => [g.fact, g.equals]))},
  {id: `${scenario.id}-recovery`, scenarioId: scenario.id, purpose: 'recovery', stages: recoveries[i], expectedCost: costs[i][1], expectedWorld: Object.fromEntries(scenario.goals.map(g => [g.fact, g.equals]))},
]);
blueprintLabWalkthroughs.push(
  {id: 'bp-hermes-stale-live-recall', scenarioId: 'bp-hermes-stale', purpose: 'alternative', expectedCost: 3, expectedWorld: {bpKilnDelivered: true}, stages: [stage([...snapshotWrite, {type: 'memory', operation: 'recall', key: 'kiln-rule'}, include('kiln-survey'), tool(act('walk-kiln-route')), tool(check('bpKilnDelivered'))])]},
  {id: 'bp-opencode-separation-connector-b', scenarioId: 'bp-opencode-separation', purpose: 'alternative', expectedCost: 3, expectedWorld: {bpConnectorDelivered: true}, stages: [stage([{type: 'lab', operation: 'select-model', providerId: 'river-ink', modelId: 'tool-b'}, {type: 'lab', operation: 'select-role', roleId: 'executor'}, tool(see('connector-order')), include('connector-order'), tool(act('connector-deliver')), tool(check('bpConnectorDelivered'))])]},
  {id: 'bp-openclaw-queue-steer', scenarioId: 'bp-openclaw-queue', purpose: 'alternative', expectedCost: 4, expectedWorld: {bpCourierDelivered: true, bpCourierReserveSafe: true, bpCrateOnCart: true}, stages: [stage([enqueue('old-courier-order'), tick('old-courier-order'), enqueue('new-courier-order', 'steer'), tick('new-courier-order'), ...queueChecks])]},
);
export const blueprintLabPrerequisites: Record<string, string[]> = {'bp-codex-approval': ['bp-codex-workbench'], 'bp-openclaw-routing': ['glasshouse-audit'], 'bp-openclaw-queue': ['bp-openclaw-routing'], 'bp-hermes-stale': ['bp-hermes-reuse'], 'bp-opencode-separation': ['glasshouse-audit'], 'bp-opencode-migration': ['bp-opencode-separation'], 'bp-pi-extension': ['bp-pi-core'], 'bp-dsh-composition': ['glasshouse-audit'], 'bp-dsh-lifecycle': ['bp-dsh-composition']};
const narrative: Array<{npc: NpcId; opening: string; hint: string; success: string; system: string; technical: string}> = [
  {npc: 'cen', opening: '岑在工作台外围画一圈，再递给你空白门令。圈内可以触及什么，与每一次动作是否获准，是两个可以分别改变的约定。', hint: '读清单与登记并核验；把工作区缩到本次三个目标。隔离与现场分别为开箱、送箱签精确许可，最后交付试验记录与验收。', success: '圈外的应急箱没有被触及。圈内的每项敏感请求分别取得许可，隔离证据也没有替代现场箱子。', system: '宿主工作区决定可写目标，角色规则决定允许、拒绝或先问；批准绑定具体请求和当前版本，两层互不扩大。', technical: 'v10 workspaceTargets 与有序角色rules独立；ask permit单次绑定call/role/realm/config/world revision。只操作虚拟目标，不能据此宣称复现Codex OS沙箱。'},
  {npc: 'ava', opening: '两只收信鸦都自称“工坊贵客”，地址却来自不同原始入口。阿芙把同一个大抽屉和两个独立抽屉摆在你面前。', hint: '按渠道与发送者分会话，再按任务推进。北岸码不该进入南岸任务；即使混进共享会话，正文也无权扩大南岸原始能力。', success: '两个入口各自完成交付，北岸私柜封好。旧失败任务仍留在原抽屉，新任务按新路由取得自己的上下文。', system: '宿主读取固定sender/channel/account/peer和replyTarget；main共享输入可能污染下一任务，但来源上限和回复目标仍独立核对。', technical: 'LabMessage来源由作者宿主声明不可被正文改写，sessionKey由路由模式确定。任务私有known决定分支；原始tools/targets拒绝共享资料诱发的越权。对应OpenClaw路由切面，不连接真实平台。'},
  {npc: 'ruin', opening: '箱子已经放上车，收信鸦又带来同一人的新地址。鲁因问你，是让旧指令跑完，还是从这个逻辑边界停下来？', hint: '推进旧任务装车，再将同源新信以interrupt入队，旧任务剩余步骤取消；新任务送南营。若旧址失败，保留装车事实再派新信。', success: '箱子没有因为改口退回仓库，旧地址也没有偷偷改成新地址。新请求带着本次来源完成了交接。', system: '队列模式处理正在等待的请求；已发生的动作与费用保留。失败旧任务、取消旧任务与新任务都有独立编号。', technical: 'followup/collect/steer/interrupt是有限逻辑边界；只允许同来源合并或改口，不提升原始权限。不是实时流式调度或OpenClaw全部队列规则。'},
  {npc: 'ava', opening: '档案架上已经是南门新律，回声这一班开工时拿到的却还是北门旧页。阿芙请你同时看存储版与启动版。', hint: '实测后修订持久规则，再开新会话取得新版启动块；也可以显式检索新版并装卷。写入不会原地刷新已经开工的块。', success: '本次炉区收到物资。存储版本和会话启动版本各有来历，新会话重新捕获资料而没有倒退世界。', system: '记忆即时持久化与本轮模型看到的启动内容不是同一件事。旧块可能仍然影响操作，需显式补资料或换会话。', technical: 'memorySnapshot保存真实entry revision与storeVersion；memory.revise增加存储版但不刷新现会话，fresh捕获新块、显式recall可补新。简化Hermes启动记忆机制，不复制系统提示或权重。'},
  {npc: 'oren', opening: '奥伦换上“执行”徽章，墨瓶却仍只会写句子。另一瓶会形成工具请求；两瓶都不会因为换标签得到一把新的门钥匙。', hint: '选支持tool-v1的有限适配器，再选有实际工具权限的执行角色。调查角色可读单，不可发箱；切角色不自动切模型。', success: '接口形成了合法工具请求，执行角色获得实际许可，诊室收到箱子。没有给任何真实型号加智力或攻击数值。', system: '连接、会话模型与工作角色分别存储；接口不支持工具时，扩大权限无济于事；只更换模型也不会改变角色范围。', technical: 'providerId/modelId/roleId独立，text-only与tool-v1仅是声明式协议教学适配。角色自有tools/rules，不承诺真实模型能力或价格。映射OpenCode分离配置切面。'},
  {npc: 'cen', opening: '桥边旧插件接不上新接口，权限纸上则把“拒绝”写在“全部允许”之前。岑不看纸标题，要你让门和工具回答。', hint: '旧API1不能激活到宿主API2；选择兼容插件。规则最后匹配生效：允许通用目标后再拒绝非委托门。门已误开时可精确批准封门再恢复窄规则。', success: '桥边物资送达，非委托门封好。兼容插件真的注册了，权限顺序也由实际允许与拒绝路径验证。', system: '迁移边界需要分别验证接口与行为。一个宽规则写在最后，会覆盖前面的拒绝；文件名和标语不决定权限。', technical: '此场只实现有限模块API兼容和原生有序V2式规则，没有V1/V2配置导入器。官方V2兼容受支持V1字段，不能将游戏API1拒绝概括为所有旧配置失效。'},
  {npc: 'ava', opening: '外来齿轮等着装入工坊。你可以信任这个项目的资源，但齿轮的执行域和挂载仍另列在一张契约上。', hint: '允许加载再激活扩展；把扩展自身设为镜砂并挂试验目标。回到扩展现场域只挂公用魔像，实际修理并验现场两目标。内置工具的镜砂不包住扩展。', success: '试验私卷只在镜砂中被复制，现场魔像修好，现场私卷未被取走。加载许可没有自动变成全目录执行权。', system: '加载信任、内置工具环境与扩展环境独立。扩展调用必须选择自己所在域与挂载，主工具沙箱不会神奇罩住其他进程。', technical: '声明式extension projectResource需trust-project，invoke只接受注册moduleId+operationId，moduleScopes.realm/mounts独立。Pi当前支持项目MCP；本游戏不执行JS/MCP/shell，也不是OS安全实现。'},
  {npc: 'oren', opening: '工坊没有固定核心，奥伦只递给你四类模块和一张依赖图。缺一根连接，真实工具便不会回应；换兼容档架也不该多出一份注册。', hint: '选择模型、循环、工具注册与格式1存储的完整依赖图，激活后读取运输单、装卷、实际发箱。换兼容档架再分别验收。', success: '完整模块图完成了运输。新档架替下旧档架，注册范围随激活图重建，箱子没有被配置按钮直接送走。', system: '模块提供与消费合同；激活只开放能力，信息输入、工具请求和世界完成仍另发生。缺依赖不能靠名字或动画补上。', technical: 'finite modules.requires/interfaceVersion/registrations实际约束请求；核心位置不可同时激活两个竞争模块。映射DeepSeek Harness组合切面，不实现Cordis或稳定SDK。'},
  {npc: 'ava', opening: '屏幕上已经闪过“送达”，档架却没保存这件事。真正的箱子与延迟回执等待配对，阿芙要求你在提交边界换架。', hint: '读运输单、实际发箱，commit真实事件后暂停。换兼容存储、power-cycle恢复已提交投影，再接回原回执、交付并验收。格式2拒绝不等于迁移成功。', success: '原请求的结果接回了，箱子没有再发一次。界面信号消失仍不影响已提交事实，旧存储注册没有继续监听。', system: '持久事件与过程UI分工；提交恢复的是已记录投影，不回滚物理世界，也不把动画当成功。请求、结果和原任务仍需配对。', technical: 'log.commit固定真实事件边界，兼容storage替换清旧注册，paused power-cycle按已提交记录恢复；protocol deferred receipt按callId/receiptId匹配。只做有限存储合同，不复制完整Harness迁移/热重载。'},
];
export const blueprintLabUiStories: Record<string, ChapterOneUiStory> = Object.fromEntries(blueprintLabScenarios.map((scenario, i) => {const n = narrative[i]; return [scenario.id, {role: 'side', location: '遗物宿主试验台', opening: n.opening, success: n.success, hint: n.hint, rules: ['模型适配、身份来源、权限与执行域分别记录，不以产品名字设战力。', '配置和激活不直接完成物理目标，消息只携带声明资料与实际回执。', '拒绝无副作用，实际失败消耗明确成本；旧任务与曝光保留。', '现实文档日期与版本另列，共有机制不是品牌独占。'], choices: [{id: 'people', text: '让原始委托人核对实际交付。', consequence: `原入口的人看到${scenario.title}的实际回执与边界。`}, {id: 'workshop', text: '给下一班留下版本与恢复记录。', consequence: `工坊为${scenario.title}保留原始输入、配置版本与恢复步骤。`}], recap: {story: n.success, system: n.system, technical: n.technical}} satisfies ChapterOneUiStory];}));
export const blueprintLabStories: ChapterOneStory[] = blueprintLabScenarios.map((scenario, i) => {const n = narrative[i], ui = blueprintLabUiStories[scenario.id]; return {id: scenario.id, title: scenario.title, track: 'side', leadNpc: n.npc, opening: [{speaker: n.npc, text: n.opening}], success: [{speaker: 'echo', text: n.success}], failureCallout: {speaker: n.npc, text: n.hint}, choicePrompt: '这次交付的证据留给谁核对？', choiceTiming: 'after-success', choices: ui.choices.map(choice => ({id: choice.id, label: choice.text, value: choice.id, reply: [{speaker: n.npc, text: choice.consequence}], consequence: {worldFlags: {[`story.${scenario.id}.evidence`]: choice.id}, trustFlags: {[n.npc]: choice.id === 'people' ? '原委托人能检查事实' : '新班次能恢复记录'}, visibleResult: choice.consequence, nextAppearance: 'harbor-hub'}})) as ChapterOneStory['choices'], unlock: {allCompleted: blueprintLabPrerequisites[scenario.id]}};});
export const blueprintLabFactLabels: Record<string, string> = {bpAliceCode: '北岸来件中的私有码', bpBobCode: '南岸来件中的私有码', bpAliceDelivered: '北岸原入口收货', bpBobDelivered: '南岸原入口收货', bpAliceCabinetClosed: '北岸私柜封好', bpLiveDestination: '当前营地实际位置', bpCrateOnCart: '运输箱已经装车', bpCourierDelivered: '当前营地实际收到', bpCourierReserveSafe: '应急箱留在原处', bpKilnRoute: '当前炉区路线', bpKilnDelivered: '炉区实际收货', bpConnectorRoute: '本次工具运输目标', bpConnectorDelivered: '工具运输真实完成', bpMigrationDelivered: '桥边物资实际收货', bpRestrictedGateClosed: '非委托门封好', bpPublicGolemReady: '现场公用魔像修好', bpScrollCopied: '当前执行域私卷被复制', bpExtensionPrivacy: '现场私卷未被复制', bpModuleRoute: '模块运输目标', bpModuleDelivered: '模块工具真实交付', bpModuleReserve: '模块运输保留物资', bpLogDestination: '日志运输实际地址', bpLogCrateAt: '实际箱子位置', bpLogReceiptMatched: '原工具结果已配对', bpLogDeliveryAck: '实际交付确认', bpLogReserveSafe: '日志运输应急箱安全'};
