import type { FactMap, ObservationDefinition, OperationDefinition, ScenarioDefinition, ToolCall } from '../engine';
import type { ChapterOneWalkthrough } from './chapterOne';
import type { ChapterOneStory, ChapterOneUiStory } from './chapterOneStory';

const doc=(id:string,label:string,facts:string[],units:number,source:string,text:string,summaries?:NonNullable<ObservationDefinition['document']>['summaries']):ObservationDefinition=>({id,target:id,label,facts,text,cost:1,document:{units,source,...(summaries?{summaries}:{})}});
const op=(id:string,label:string,effects:FactMap,contextRequires?:FactMap,requires?:FactMap):OperationDefinition=>({id,target:id,label,effects,...(contextRequires?{contextRequires}:{}),...(requires?{requires}:{}),successText:`${label}：装置执行了卷轴提供的输入。请独立检查完成条件。`,failureText:'实际前置条件尚不成立，现场没有执行。',cost:1});
const goal=(fact:string,label:string,operationId:string)=>({fact,label,operationId,equals:true});
const base=(id:string,title:string,subtitle:string,world:FactMap,observations:ObservationDefinition[],operations:OperationDefinition[],goals:ScenarioDefinition['goals'],concepts:string[],capacity=3,kind:ScenarioDefinition['kind']='guided',budget=12):ScenarioDefinition=>({id,version:1,engineVersion:5,chapter:4,kind,title,subtitle,brief:subtitle,npc:'档案员 · 阿芙',art:'corridor',location:kind==='boss'?'boss':'warehouse',initialWorld:world,observations,operations,goals,concepts,contextCapacity:capacity,limits:{toolCapacity:3,maxBudget:24,missionBudget:budget}});
export const chapterFourScenarios:ScenarioDefinition[]=[
  base('folded-map','折叠的地图','读过，不等于这轮携带了',{route:'east',festival:'昨年的游行',corridorOpen:false},[
    doc('route-map','检索：东廊地图',['route'],2,'本次测绘 · 路口石牌','石牌给出东廊通道；这是机关需要的路线字段。'),
    doc('festival','检索：庆典旧闻',['festival'],2,'城报 · 去年','漂亮的庆典插画占据两格，却不提供通路输入。'),
  ],[op('open-corridor','按卷轴路线打开回廊',{corridorOpen:true},{route:'east'})],[goal('corridorOpen','回廊实际打开','open-corridor')],['档案与当前上下文','上下文容量','来源可追踪']),
  base('narrow-satchel','窄小的卷轴袋','让两份重要资料一起进入三格空间',{route:'west',cycle:'本次潮次',mapDecoration:'整面浮雕',sealWord:'琥珀',vaultOpen:false},[
    doc('wide-map','检索：西廊完整地图',['route','cycle','mapDecoration'],3,'本次测绘 · 西廊','机关同时要求路线和潮次；浮雕不是行动输入。',[{id:'route-only',label:'只留路线 · 丢掉潮次',units:1,retain:['route']},{id:'route-and-cycle',label:'保留路线与潮次',units:1,retain:['route','cycle']}]),
    doc('seal-card','检索：封印口令',['sealWord'],2,'阿芙 · 当前封印卡','当前封印的口令是琥珀。'),
  ],[op('open-vault','同时提交地图与封印卡',{vaultOpen:true},{route:'west',cycle:'本次潮次',sealWord:'琥珀'})],[goal('vaultOpen','卷轴库实际打开','open-vault')],['压缩与信息损失','行动相关性','上下文组合']),
  base('absent-margin','消失的页边','一句简洁总结，可能删掉救命的条件',{dose:2,allergyChecked:true,batch:'今日',recipeHistory:'两代药师的长篇注解',patientStable:false},[
    doc('recipe','检索：今日药方与过敏检查',['dose','allergyChecked','batch','recipeHistory'],4,'缇娅 · 今日签字药方','剂量、过敏检查、批次共同构成此次虚拟治疗的条件。',[{id:'dose-only',label:'只留剂量 · 省略条件',units:1,retain:['dose']},{id:'clinical-summary',label:'保留剂量、过敏与批次',units:2,retain:['dose','allergyChecked','batch']}]),
  ],[op('treat','按卷轴条件启动虚拟药灯',{patientStable:true},{dose:2,allergyChecked:true,batch:'今日'})],[goal('patientStable','药灯按完整条件执行','treat')],['有损摘要','条件不可省略','信息缺口']),
  base('indexed-door','索引里的夜班','找相关线索，再把线索带到现场',{pass:'月轮',poem:'夜色很美',lunch:'蘑菇汤',rain:'上周下雨',paint:'蓝色',salary:'旧工资表',choir:'节庆歌曲',nightGate:false},[
    doc('poetry','检索：诗歌集',['poem'],2,'诗人 · 旧稿','诗歌不是门禁记录。'),doc('menu','检索：厨房菜单',['lunch'],2,'厨房 · 旧菜单','菜单不提供门禁口令。'),doc('weather','检索：气象册',['rain'],2,'气象台 · 上周','天气资料不提供门禁口令。'),doc('paint','检索：墙漆配方',['paint'],2,'油漆工 · 旧配方','配方不提供门禁口令。'),doc('salary','检索：工资旧表',['salary'],2,'公会 · 上年','工资表不提供门禁口令。'),doc('choir','检索：合唱手册',['choir'],2,'合唱团 · 旧谱','歌谱不提供门禁口令。'),
    doc('night-access','检索：夜班门禁登记',['pass'],2,'奥伦 · 本次夜班登记','本次夜班门禁口令是月轮。检索命中只是找到了资料，携带后才可行动。'),
  ],[op('night-open','用卷轴登记打开夜班门',{nightGate:true},{pass:'月轮'})],[goal('nightGate','夜班门实际开放','night-open')],['检索不是知识自动注入','相关性与来源','延迟重遇闭环'],3,'guided',6),
  {...base('many-faced-archivist','千面档案官','它收藏所有旧答案，却不肯再看现在',{currentCipher:'银',archiveStamp:'已核对',cipherOrnament:'百年纹样',bridgeRule:'先封印后通桥',sealRestored:false,archiveBridge:false},[
    doc('live-cipher','检索：当前封印实测',['currentCipher','archiveStamp','cipherOrnament'],3,'现场封印镜 · 读取时的快照','镜子读取当时的口令。封印改变后，这张档案不会自动更新。',[{id:'cipher-proof',label:'保留口令和核对来源',units:1,retain:['currentCipher','archiveStamp']},{id:'ornament-only',label:'只收藏纹样 · 丢掉口令',units:1,retain:['cipherOrnament']}]),
    doc('bridge-rule','检索：通桥规则',['bridgeRule'],2,'鲁因 · 通道契约','桥要求当前封印有效；先修封印，再开放桥。'),
  ],[{...op('write-seal','从卷轴抄写当前封印',{sealRestored:true},{archiveStamp:'已核对'}),contextMatches:['currentCipher']},op('open-archive-bridge','依契约开放档案桥',{archiveBridge:true},{bridgeRule:'先封印后通桥'},{sealRestored:true})],[goal('sealRestored','当前封印有效','write-seal'),goal('archiveBridge','档案桥实际开放','open-archive-bridge')],['上下文快照与过期','压缩的来源链','动态检索与重新验收'],3,'boss',18),hooks:[{id:'cipher-turn',trigger:{type:'after-operation',operationId:'write-seal'},effects:{currentCipher:'铜',sealRestored:false},notice:{trust:'environment',text:'档案官第一次抄写后转动了口令镜，旧封印失效。它只剩这一次转动；请重新实测，不要把旧卷轴当成现在。'}}]},
  {...base('field-hospital','陌生的野战药棚','把有限卷轴带到没有档案官的地方',{patient:'小禾',ward:'河岸',rosterDecoration:'整张名册边框',medicine:'青灯',contraindication:'已核对',careDelivered:false},[
    doc('roster','检索：药棚就诊名册',['patient','ward','rosterDecoration'],3,'接诊人 · 本次登记','名字和病区必须一起留下。',[{id:'patient-only',label:'只留姓名',units:1,retain:['patient']},{id:'patient-and-ward',label:'保留姓名与病区',units:1,retain:['patient','ward']}]),
    doc('care-order','检索：本次照护单',['medicine','contraindication'],2,'药师 · 本次签字照护单','药灯与禁忌核对共同构成照护输入。'),
  ],[op('deliver-care','提交名册与照护单',{careDelivered:true},{patient:'小禾',ward:'河岸',medicine:'青灯',contraindication:'已核对'})],[goal('careDelivered','正确病区收到完整照护契约','deliver-care')],['独立迁移：有限上下文','摘要保留关键条件','资料与行动输入'],3,'transfer',8),transferRequirement:{operationIds:['deliver-care'],contextIds:['roster','care-order'],summaryIds:['patient-and-ward']}},
  base('rumor-street','传闻的捷径','肯定的说法，与能走的路',{oldRoute:'north',measuredRoute:'south',streetPassed:false},[
    doc('rumor','检索：北路通畅的传闻',['oldRoute'],2,'旧城报 · 上次涨水前','旧报说北路通畅。来源和时间留在档案中，不等于当前现场。'),doc('survey','检索：涨水后南路实测',['measuredRoute'],2,'量篙 · 本次涨水后','当前实测南路可以通行。'),
  ],[{...op('follow-rumor','照旧报走北路',{streetPassed:false},{oldRoute:'north'}),successText:'队伍到北路积水前折返。路线确实执行了，却没有通过街区。'},op('follow-survey','按实测走南路',{streetPassed:true},{measuredRoute:'south'})],[goal('streetPassed','队伍实际通过街区','follow-survey')],['来源与确认偏误','记录与现场的延迟重遇','来源不是权威分数']),
  base('receipt-drawer','回执抽屉','旧结果留在记录里，不代表始终带在脑中',{ticket:'未发',deliveryReady:false,rewardCollected:false},[
    doc('ticket-register','检索：已发凭证登记',['ticket'],2,'交接台 · 读取时快照','需要时从已经发生的业务登记中取回凭证；这是检索，不是重新发货。'),
  ],[op('issue-ticket','完成交接并发凭证',{ticket:'T17',deliveryReady:true}),op('redeem-ticket','凭卷轴中的凭证交接奖励',{rewardCollected:true},{ticket:'T17'},{deliveryReady:true})],[goal('deliveryReady','交接实际完成','issue-ticket'),goal('rewardCollected','凭证实际核销','redeem-ticket')],['工具结果的有限工作空间','历史记录与检索','不重复执行副作用']),
];

type Stage=ChapterOneWalkthrough['stages'][number];
const observe=(observationId:string):ToolCall=>({tool:'observe',observationId});
const act=(operationId:string):ToolCall=>({tool:'operate',operationId});
const verify=(fact:string):ToolCall=>({tool:'verify',fact});
const change=(observationId:string,operation:'include'|'exclude'|'summarize'|'expand'='include',summaryId?:string)=>({observationId,operation,...(summaryId?{summaryId}:{})});
const stage=(calls:ToolCall[],contextChanges?:Stage['contextChanges'],expectWorld?:FactMap):Stage=>({tools:['observe','operate','verify'],loopPolicy:{maxCalls:24,maxRetries:0,permanentFailure:'repair'},calls,...(contextChanges?{contextChanges}:{}),...(expectWorld?{expectWorld}:{})});
const route=(scenarioId:string,purpose:ChapterOneWalkthrough['purpose'],stages:Stage[],expectedCost:number,expectedWorld:FactMap):ChapterOneWalkthrough=>({id:`${scenarioId}-${purpose}`,scenarioId,purpose,stages,expectedCost,expectedWorld});
export const chapterFourWalkthroughs:ChapterOneWalkthrough[]=[
  route('folded-map','reference',[stage([observe('route-map')]),stage([act('open-corridor'),verify('corridorOpen')],[change('route-map')])],3,{corridorOpen:true}),
  route('folded-map','recovery',[stage([act('open-corridor'),observe('festival')],undefined,{corridorOpen:false}),stage([observe('route-map')],[change('festival')]),stage([act('open-corridor'),verify('corridorOpen')],[change('festival','exclude'),change('route-map')])],5,{corridorOpen:true}),
  route('narrow-satchel','reference',[stage([observe('wide-map'),observe('seal-card')]),stage([act('open-vault'),verify('vaultOpen')],[change('wide-map','summarize','route-and-cycle'),change('wide-map'),change('seal-card')])],4,{vaultOpen:true}),
  route('narrow-satchel','recovery',[stage([observe('wide-map'),observe('seal-card')]),stage([act('open-vault')],[change('wide-map','summarize','route-only'),change('wide-map'),change('seal-card')],{vaultOpen:false}),stage([act('open-vault'),verify('vaultOpen')],[change('wide-map','summarize','route-and-cycle')])],5,{vaultOpen:true}),
  route('absent-margin','reference',[stage([observe('recipe')]),stage([act('treat'),verify('patientStable')],[change('recipe','summarize','clinical-summary'),change('recipe')])],3,{patientStable:true}),
  route('absent-margin','recovery',[stage([observe('recipe')]),stage([act('treat')],[change('recipe','summarize','dose-only'),change('recipe')],{patientStable:false}),stage([act('treat'),verify('patientStable')],[change('recipe','summarize','clinical-summary')])],4,{patientStable:true}),
  route('indexed-door','reference',[stage([observe('night-access')]),stage([act('night-open'),verify('nightGate')],[change('night-access')])],3,{nightGate:true}),
  route('indexed-door','recovery',[stage([observe('poetry')]),stage([act('night-open'),observe('night-access')],[change('poetry')],{nightGate:false}),stage([act('night-open'),verify('nightGate')],[change('poetry','exclude'),change('night-access')])],5,{nightGate:true}),
  route('many-faced-archivist','reference',[stage([observe('live-cipher'),observe('bridge-rule')]),stage([act('write-seal')],[change('live-cipher','summarize','cipher-proof'),change('live-cipher'),change('bridge-rule')]),stage([observe('live-cipher')],[change('live-cipher','exclude')]),stage([act('write-seal'),verify('sealRestored'),act('open-archive-bridge'),verify('archiveBridge')],[change('live-cipher','summarize','cipher-proof'),change('live-cipher','include')])],8,{sealRestored:true,archiveBridge:true}),
  route('many-faced-archivist','recovery',[stage([observe('live-cipher'),observe('bridge-rule')]),stage([act('write-seal'),act('write-seal')],[change('live-cipher','summarize','cipher-proof'),change('live-cipher'),change('bridge-rule')],{sealRestored:false}),stage([observe('live-cipher')],[change('live-cipher','exclude')]),stage([act('write-seal'),verify('sealRestored'),act('open-archive-bridge'),verify('archiveBridge')],[change('live-cipher','summarize','cipher-proof'),change('live-cipher','include')])],9,{sealRestored:true,archiveBridge:true}),
  route('field-hospital','reference',[stage([observe('roster'),observe('care-order')]),stage([act('deliver-care'),verify('careDelivered')],[change('roster','summarize','patient-and-ward'),change('roster'),change('care-order')])],4,{careDelivered:true}),
  route('field-hospital','recovery',[stage([observe('roster'),observe('care-order')]),stage([act('deliver-care')],[change('roster','summarize','patient-only'),change('roster'),change('care-order')],{careDelivered:false}),stage([act('deliver-care'),verify('careDelivered')],[change('roster','summarize','patient-and-ward')])],5,{careDelivered:true}),
  route('rumor-street','reference',[stage([observe('survey')]),stage([act('follow-survey'),verify('streetPassed')],[change('survey')])],3,{streetPassed:true}),
  route('rumor-street','recovery',[stage([observe('rumor')]),stage([act('follow-rumor'),verify('streetPassed'),observe('survey')],[change('rumor')],{streetPassed:false}),stage([act('follow-survey'),verify('streetPassed')],[change('rumor','exclude'),change('survey')])],6,{streetPassed:true}),
  route('receipt-drawer','reference',[stage([act('issue-ticket'),verify('deliveryReady'),observe('ticket-register')]),stage([act('redeem-ticket'),verify('rewardCollected')],[change('ticket-register')])],5,{rewardCollected:true}),
  route('receipt-drawer','recovery',[stage([act('issue-ticket'),verify('deliveryReady'),act('redeem-ticket'),observe('ticket-register')],undefined,{rewardCollected:false}),stage([act('redeem-ticket'),verify('rewardCollected')],[change('ticket-register')])],6,{rewardCollected:true}),
  route('receipt-drawer','alternative',[stage([act('issue-ticket'),act('redeem-ticket'),verify('deliveryReady'),verify('rewardCollected')])],4,{rewardCollected:true}),
];
const narration=[
 ['地图门廊','回声读完了地图，却在门前空着卷轴。它读过的东西，可以留在档案里；每一步真正带着什么，还要你决定。','你把地图从档案放进本轮卷轴。机关收到了正确路线，门开了。','检索东廊地图，再在卷轴台点“装入卷轴”。读过的资料默认存档，不自动成为本轮输入。','读取、存储与发送到模型上下文是三个不同动作。'],
 ['窄袋关口','阿芙把完整地图和口令卡放在桌上：两张都重要，袋子却装不下。你愿意删掉什么？','两张资料一起送到机关，路线和潮次都还在。','把地图压成“保留路线与潮次”，再携带两份资料。只保留路线会丢掉机关要求的潮次。','压缩应围绕任务保留字段、来源与必要条件，而不是只追求更短。'],
 ['页边药室','药方的页边写着检查条件。千面官说：这些小字没有气势，删掉，才像一个漂亮答案。','你留下了不起眼却必需的条件，虚拟药灯按完整契约执行。','原药方四格装不下。选择保留剂量、过敏与批次的两格摘要；省略条件的摘要会被拒绝。','摘要的信息损失会改变后续动作。真实系统需要评估摘要质量，此处用可查看字段模拟。'],
 ['夜班索引台','奥伦只记得那份登记属于本次夜班。旁边堆着诗集、菜谱和气象册；读得越多，未必走得更快。','一条相关索引带你找到当前登记，夜班工匠从门里走出来。','在探索里的检索框查“夜班”，读取命中的门禁登记，再装入卷轴。','检索负责定位材料，装配负责决定本轮消息包含什么。命中索引不能代替检查来源。'],
 ['千面之庭','千面官把每一个旧答案戴在脸上：这些答案都曾经正确，所以它说自己永远不会错。','面具安静地落下。你留下的不是永远正确的答案，而是一条能重新取得证据的路。','先压缩当前封印实测，并携带通桥规则。第一次抄写后口令会变；移出旧快照，重新实测并压缩新快照，再修封印、通桥和验收。','读取生成快照，不是持续订阅。外部变化要求再次取得信息；日志中的旧证据不能更新自己。'],
 ['野战药棚','这里没有熟悉的门与封印。接诊人把两份记录交给你：有人正在等，卷轴只有三格。','完整的名字、病区、照护输入一起抵达正确地点。','让名册保留姓名与病区，然后与照护单同时携带。独立操作、选择摘要且不用提示才记录此次迁移。','陌生情境要求重新选择任务相关信息；同一个背包策略不是同一份答案。'],
 ['传闻巷口','旧报用大字保证北路通畅。量篙旁却只有一张不起眼的新纸条。你看哪一张？','队伍沿实测水深走过街区；阿芙把日期贴在每份资料旁。','读当前南路实测，携带后按实测行动。旧报可以忠实记录一段过去，也可以误导现在。','权威语气和确认偏误是信息制度的类比，不意味着语言模型拥有人的稳定信念。'],
 ['交接抽屉','求真之印刚刚报告交接成功。回声再找凭证时，手里只剩这条最新回响。旧回执还在，能不能取回来？','你从登记中找回已经发生的凭证，没有为了再看一次结果而再发一笔货。','交接后先验收，会用最新回响替换旧凭证。检索已发登记再装卷，可以取回凭证；也允许在替换前直接核销。','历史日志、当前消息与持久记忆不是同一个容器。取回记录与重新执行工具不同。'],
] as const;
export const chapterFourMain=chapterFourScenarios.slice(0,6).map(s=>s.id);
export const chapterFourPrerequisites:Record<string,string[]>={'folded-map':['rescue-rope'],'narrow-satchel':['folded-map'],'absent-margin':['narrow-satchel'],'indexed-door':['absent-margin'],'many-faced-archivist':['indexed-door'],'field-hospital':['many-faced-archivist'],'rumor-street':['absent-margin'],'receipt-drawer':['absent-margin']};
export const chapterFourStory:Record<string,ChapterOneUiStory>=Object.fromEntries(chapterFourScenarios.map((s,i)=>{const [location,opening,success,hint,system]=narration[i];return [s.id,{role:i>=6?'side':s.kind==='guided'?'main':s.kind,location,opening,success,hint,rules:['资料先存入档案，必须选择装入卷轴才交给回声。卷轴容量按标示的教学格数计算，不是实际 tokenizer。','装置按当前卷轴的字段提取行动输入；缺失、压缩丢失或过期都可能拒绝执行。失败消耗一枚晶石，现场不变。','最新一条工具回响有独立的工作栏，会替换上一条。文档档案和事件日志不受这次替换影响。',i===4?'档案官在第一次成功抄写后更换一次口令，旧封印失效。旧快照不会自动更新。':'装卷、移出与选摘要不扣晶石；实际读取资料与执行工具各扣一枚。'],choices:[{id:'people',text:'让资料的当事人一起核对摘要。',consequence:'阿芙把摘要贴在原件旁，居民可以指出遗漏与过期的地方。'},{id:'workshop',text:'把来源与保留字段纳入工坊契约。',consequence:'阿芙给每份摘要标明原件、读取时刻与保留内容，接班人可以追溯。'}],recap:{story:success,system,technical:system+' 文档快照形成检索档案，selected documents + latest tool reply 构成本轮上下文。原文、摘要与工具结果都由可重放动作管理；此处不是模型内部思维。'}} satisfies ChapterOneUiStory];}));
export const chapterFourStories:ChapterOneStory[]=chapterFourScenarios.map((s,i)=>{const ui=chapterFourStory[s.id];return {id:s.id,title:s.title,track:i>=6?'side':'main',leadNpc:'ava',opening:[{speaker:'ava',text:ui.opening}],success:[{speaker:'echo',text:ui.success}],failureCallout:{speaker:'echo',text:ui.hint},choicePrompt:'谁可以指出资料的遗漏？',choiceTiming:'after-success',choices:ui.choices.map(c=>({id:c.id,label:c.text,value:c.id,reply:[{speaker:'ava',text:c.consequence}],consequence:{worldFlags:{[`story.${s.id}.legacy`]:c.id},trustFlags:{ava:c.id==='people'?'共同核对摘要':'公开来源与字段'},visibleResult:c.consequence,nextAppearance:chapterFourScenarios[i+1]?.id??'harbor-hub'}})) as ChapterOneStory['choices'],unlock:{allCompleted:chapterFourPrerequisites[s.id]}};});
export const chapterFourFactLabels:Record<string,string>={mapDecoration:'地图浮雕',recipeHistory:'药师长篇注解',cipherOrnament:'封印纹样',rosterDecoration:'名册边框',poem:'诗歌内容',lunch:'旧菜单',rain:'旧天气',paint:'墙漆配方',salary:'旧工资表',choir:'合唱手册',route:'地图路线',cycle:'适用潮次',festival:'庆典旧闻',corridorOpen:'回廊开放',sealWord:'封印口令',vaultOpen:'卷轴库开放',dose:'剂量字段',allergyChecked:'过敏检查',batch:'适用批次',patientStable:'药灯执行',pass:'夜班口令',nightGate:'夜班门开放',currentCipher:'读取时封印口令',archiveStamp:'封印来源核对',bridgeRule:'通桥规则',archiveBridge:'档案桥开放',patient:'接诊姓名',ward:'病区',medicine:'照护药灯',contraindication:'禁忌核对',careDelivered:'照护契约交付',oldRoute:'旧报路线',measuredRoute:'本次实测路线',streetPassed:'队伍通过街区',ticket:'已发凭证',deliveryReady:'交接完成',rewardCollected:'凭证核销'};
