import {blueprintTrialStories,blueprintTrialUiStories} from './blueprintTrials';
import {seasonBookendStories,seasonBookendStory} from './seasonBookends';
import {chapterEightStories,chapterEightStory} from './chapterEight';
import { chapterSevenStories, chapterSevenStory } from './chapterSeven';
import { chapterSixStories, chapterSixStory } from './chapterSix';
import { chapterFiveStories, chapterFiveStory } from './chapterFive';
import { chapterOneStories, chapterOneStory } from './chapterOneStory';
import { chapterTwoStories, chapterTwoStory } from './chapterTwo';
import { chapterThreeStories, chapterThreeStory } from './chapterThree';
import { chapterFourStories, chapterFourStory } from './chapterFour';
export const stories = [...chapterOneStories, ...chapterTwoStories, ...chapterThreeStories, ...chapterFourStories,...chapterFiveStories,...chapterSixStories,...chapterSevenStories,...chapterEightStories,...seasonBookendStories,...blueprintTrialStories];
export const uiStories = {...chapterOneStory, ...chapterTwoStory, ...chapterThreeStory,...chapterFourStory,...chapterFiveStory,...chapterSixStory,...chapterSevenStory,...chapterEightStory,...seasonBookendStory,...blueprintTrialUiStories};
