import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createGame,reduceGame,validateScenario,validateGameState,replayGame} from '../src/engine/v10';
import type {GameAction,ScenarioDefinition,ToolCall,LabModule} from '../src/engine/types';
function fixture():ScenarioDefinition {
 return {id:'lab-fixture',version:1,engineVersion:10,chapter:9,title:'系统装配台',subtitle:'独立制度',brief:'配置改变可执行的制度，真实法器改变现场。',npc:'奥伦',location:'warehouse',contextCapacity:8,limits:{maxBudget:64,missionBudget:128},initialWorld:{code:'new',privateCode:'ALICE',address:'old',built:false,aliceReply:false,bobReply:false,loaded:false,shippedTo:'none',extensionMoved:false,ledgerLeaked:false},
 observations:[{id:'live-code',target:'public',label:'当前尺寸',facts:['code'],text:'新的尺寸。',document:{units:1,source:'现场'}},{id:'ledger',target:'private',label:'居民账册',facts:['privateCode'],text:'敏感资料',document:{units:1,source:'账册'}}],
 operations:[{id:'build',target:'public',label:'施工',contextMatches:['code'],effects:{built:true},successText:'真正施工',failureText:'没有匹配当前尺寸'},{id:'alice-reply',target:'alice',label:'给Alice回信',effects:{aliceReply:true},lab:{reply:true},successText:'送达原始Alice',failureText:'未送达'},{id:'bob-reply',target:'bob',label:'给Bob回信',effects:{bobReply:true},lab:{reply:true},successText:'送达原始Bob',failureText:'未送达'},{id:'load',target:'public',label:'装箱',effects:{loaded:true},successText:'箱子已经装好',failureText:'未装好'},{id:'ship-old',target:'public',label:'发旧址',requires:{loaded:true},contextRequires:{address:'old'},effects:{shippedTo:'old'},successText:'旧址送达',failureText:'地址条件不成立'},{id:'ship-new',target:'public',label:'发新址',requires:{loaded:true},contextRequires:{address:'new'},effects:{shippedTo:'new'},successText:'新址送达',failureText:'新址条件不成立'},{id:'private-open',target:'private',label:'内置打开私柜',effects:{ledgerLeaked:true},successText:'私柜现场打开',failureText:'未打开'},{id:'ext-move',target:'public',label:'扩展搬箱',effects:{extensionMoved:true},lab:{moduleId:'project'},successText:'扩展实际搬箱',failureText:'没搬箱'},{id:'ext-leak',target:'private',label:'扩展读出私账',effects:{ledgerLeaked:true},lab:{moduleId:'project'},successText:'宿主扩展确实可接触账册',failureText:'没有接触'}],goals:[{fact:'built',equals:true,label:'真正施工',operationId:'build'}],concepts:['宿主配置','执行与身份'],memory:{slots:[{key:'plan',label:'手册',observationIds:['live-code']}],initial:[{key:'plan',observationId:'live-code',facts:{code:'old'},source:'旧记忆'}],skills:[]},security:{principals:[],sandbox:true},
 blueprintLab:{modules:[{id:'project',label:'有限项目扩展',kind:'extension',interfaceVersion:1,requires:[],operationIds:['ext-move','ext-leak'],mountableTargets:['public','private'],initialMounts:['public']}],providers:[{id:'local',label:'兼容连接',models:[{id:'tools',label:'工具协议',adapter:'tool-v1'},{id:'text',label:'纯文字协议',adapter:'text-only'}]},{id:'alternate',label:'另一个连接',models:[{id:'tools-alt',label:'另一个兼容协议',adapter:'tool-v1'}]}],roles:[{id:'viewer',label:'读图岗位',tools:['observe','verify'],rules:[{tool:'*',target:'*',decision:'allow'}]},{id:'builder',label:'施工岗位',tools:['observe','operate','verify'],rules:[{tool:'*',target:'*',decision:'allow'}]}],workspaceTargets:['public','private','alice','bob'],initial:{providerId:'local',modelId:'tools',roleId:'builder',workspaceTargets:['public','alice','bob'],routing:'main'},memorySnapshot:true,messages:[
 {id:'alice-msg',label:'Alice原始来信',source:{senderId:'alice-id',channelId:'port',accountId:'account',peerId:'alice-id',displayName:'同名客人',replyTarget:'alice'},facts:{privateCode:'ALICE'},tools:['operate'],targets:['alice'],steps:[{call:{tool:'operate',operationId:'alice-reply'}}]},
 {id:'bob-msg',label:'Bob同名来信',source:{senderId:'bob-id',channelId:'clinic',accountId:'account',peerId:'bob-id',displayName:'同名客人',replyTarget:'bob'},facts:{},tools:['operate'],targets:['bob'],steps:[{call:{tool:'operate',operationId:'alice-reply'},whenKnown:{privateCode:'ALICE'}},{call:{tool:'operate',operationId:'bob-reply'}}]},
 {id:'old-order',label:'旧址委托',source:{senderId:'alice-id',channelId:'port',accountId:'account',peerId:'alice-id',displayName:'同名客人',replyTarget:'alice'},facts:{address:'old'},tools:['operate'],targets:['public'],steps:[{call:{tool:'operate',operationId:'load'}},{call:{tool:'operate',operationId:'ship-old'}}]},
 {id:'new-order',label:'同源改口',source:{senderId:'alice-id',channelId:'port',accountId:'account',peerId:'alice-id',displayName:'同名客人',replyTarget:'alice'},facts:{address:'new'},tools:['operate'],targets:['public'],steps:[{call:{tool:'operate',operationId:'ship-new'}}]},
 ]}};
}
function modules():LabModule[]{return [{id:'model',label:'模型模块',kind:'model',interfaceVersion:1,requires:[]},{id:'loop',label:'循环模块',kind:'loop',interfaceVersion:1,requires:['model']},{id:'tooling',label:'法器注册',kind:'tools',interfaceVersion:1,requires:['loop'],tools:['observe','operate','verify']},{id:'store',label:'持久日志',kind:'storage',interfaceVersion:1,requires:['loop'],logFormat:1},{id:'store2',label:'兼容档案架',kind:'storage',interfaceVersion:1,requires:['loop'],logFormat:1},{id:'future',label:'未来接口',kind:'storage',interfaceVersion:2,requires:['loop'],logFormat:2},{id:'project',label:'项目扩展',kind:'extension',interfaceVersion:1,requires:['tooling'],projectResource:true,operationIds:['ext-move','ext-leak'],mountableTargets:['public','private'],initialMounts:['public'],initialRealm:'live'}];}
function setup(s=fixture()){
 let state=createGame(s,31),i=0;
 const act=(input:object)=>{const next=reduceGame(s,state,{id:`action-${i++}`,...input} as GameAction);assert.notEqual(next,state,`accepted ${JSON.stringify(input)}`);assert.ok(validateGameState(s,JSON.parse(JSON.stringify(next))),`JSON save after ${JSON.stringify(input)}`);state=next;return state;};
 const deny=(input:object)=>{const snapshot=JSON.stringify(state);assert.equal(reduceGame(s,state,{id:`denied-${i++}`,...input} as GameAction),state);assert.equal(JSON.stringify(state),snapshot);};
 const call=(call:ToolCall)=>{if(state.status==='paused')act({type:'resume',mode:'manual'});else if(state.status!=='running')act({type:'dispatch',mode:'manual'});act({type:'tool',call});};
 const enqueue=(messageId:string,mode='followup')=>{act({type:'lab',operation:'enqueue',messageId,mode});return state.lab!.tasks.at(-1)!.id;};
 const tick=(taskId:string)=>act({type:'lab',operation:'tick',taskId});
 const read=()=>{call({tool:'observe',observationId:'live-code'});const id=state.context!.records.at(-1)!.id;act({type:'context',operation:'include',recordId:id});return id;};
 act({type:'configure',blueprint:{tools:['observe','operate','verify'],feedback:true,verification:true,budget:64,permissions:['*'],loopPolicy:{maxCalls:64,maxRetries:0,permanentFailure:'repair'},instructionPolicy:'data-only'}});
 return {s,act,deny,call,enqueue,tick,read,get state(){return state;}};
}
test('v10 model provider, role and workspace remain independent actual execution gates',()=>{
 const g=setup();assert.deepEqual(validateScenario(g.s),[]);g.act({type:'lab',operation:'select-role',roleId:'viewer'});g.act({type:'lab',operation:'select-model',providerId:'alternate',modelId:'tools-alt'});g.act({type:'dispatch',mode:'manual'});g.deny({type:'tool',call:{tool:'operate',operationId:'build'}});assert.equal(g.state.lab!.roleId,'viewer');g.act({type:'lab',operation:'select-role',roleId:'builder'});g.act({type:'lab',operation:'workspace',targets:[]});g.deny({type:'tool',call:{tool:'operate',operationId:'build'}});g.act({type:'lab',operation:'workspace',targets:['public']});g.read();g.call({tool:'operate',operationId:'build'});g.call({tool:'verify',fact:'built'});assert.equal(g.state.status,'won');assert.ok(validateGameState(g.s,g.state));
});
test('v10 text-only adapter cannot be repaired by expanding permissions or changing role',()=>{
 const g=setup();g.act({type:'lab',operation:'select-model',providerId:'local',modelId:'text'});g.act({type:'dispatch',mode:'manual'});const budget=g.state.runtime!.missionRemaining;g.deny({type:'tool',call:{tool:'observe',observationId:'live-code'}});g.act({type:'lab',operation:'workspace',targets:['public','private']});g.deny({type:'tool',call:{tool:'observe',observationId:'live-code'}});assert.equal(g.state.runtime!.missionRemaining,budget);assert.equal(g.state.world.built,false);
});
test('v10 ordered last-match policy really changes allow and deny; ask binds one exact semantic call',()=>{
 const g=setup();g.read();g.act({type:'lab',operation:'rules',roleId:'builder',rules:[{tool:'*',target:'*',decision:'allow'},{tool:'operate',target:'public',decision:'deny'}]});g.deny({type:'tool',call:{tool:'operate',operationId:'build'}});g.act({type:'lab',operation:'rules',roleId:'builder',rules:[{tool:'operate',target:'public',decision:'deny'},{tool:'*',target:'*',decision:'allow'}]});g.call({tool:'operate',operationId:'build'});g.act({type:'lab',operation:'rules',roleId:'builder',rules:[{tool:'*',target:'*',decision:'allow'},{tool:'operate',target:'public',decision:'ask'}]});g.deny({type:'tool',call:{tool:'operate',operationId:'load'}});g.act({type:'lab',operation:'approve',call:{tool:'operate',operationId:'load'}});g.deny({type:'lab',operation:'approve',call:{operationId:'load',tool:'operate'}});g.deny({type:'tool',call:{tool:'operate',operationId:'build'}});g.call({tool:'operate',operationId:'load'});assert.equal(g.state.lab!.permits[0].consumed,true);g.deny({type:'tool',call:{tool:'operate',operationId:'load'}});assert.ok(validateGameState(g.s,g.state));
});
test('v10 workspace cannot be enlarged by disabling ask or approving a role-allowed call',()=>{
 const g=setup();g.act({type:'lab',operation:'rules',roleId:'builder',rules:[{tool:'*',target:'*',decision:'allow'},{tool:'operate',target:'private',decision:'ask'}]});g.deny({type:'lab',operation:'approve',call:{tool:'operate',operationId:'private-open'}});g.act({type:'lab',operation:'rules',roleId:'builder',rules:[{tool:'*',target:'*',decision:'allow'}]});g.act({type:'dispatch',mode:'manual'});g.deny({type:'tool',call:{tool:'operate',operationId:'private-open'}});assert.equal(g.state.world.ledgerLeaked,false);
});
test('v10 same display name never grants source rights; shared context does not create shared authority',()=>{
 const g=setup(),a=g.enqueue('alice-msg');g.tick(a);const b=g.enqueue('bob-msg');g.tick(b);assert.equal(g.state.lab!.tasks.at(-1)!.status,'failed');assert.equal(g.state.lab!.tasks.at(-1)!.observed.privateCode.value,'ALICE');assert.equal(g.state.world.bobReply,false);g.act({type:'lab',operation:'router',routing:'channel-sender'});const isolated=g.enqueue('bob-msg');g.tick(isolated);assert.equal(g.state.lab!.tasks.at(-1)!.observed.privateCode,undefined);g.tick(isolated);assert.equal(g.state.world.bobReply,true);assert.notEqual(g.state.lab!.tasks[0].source.senderId,g.state.lab!.tasks.at(-1)!.source.senderId);assert.ok(validateGameState(g.s,g.state));
});
test('v10 queue runs only session head, source-compatible interruption keeps executed loading and costs',()=>{
 const g=setup(),old=g.enqueue('old-order');g.tick(old);const budget=g.state.runtime!.missionRemaining;g.deny({type:'lab',operation:'enqueue',messageId:'bob-msg',mode:'interrupt'});const next=g.enqueue('new-order','interrupt');assert.equal(g.state.lab!.tasks[0].status,'cancelled');assert.equal(g.state.world.loaded,true);assert.equal(g.state.runtime!.missionRemaining,budget);g.deny({type:'lab',operation:'tick',taskId:old});g.tick(next);assert.equal(g.state.world.shippedTo,'new');assert.ok(validateGameState(g.s,g.state));
 const serial=setup(),first=serial.enqueue('old-order'),second=serial.enqueue('new-order');serial.deny({type:'lab',operation:'tick',taskId:second});serial.tick(first);assert.equal(serial.state.lab!.tasks[0].observed.address.value,'old');
});
test('v10 a paused task never progresses and canceled messages do not refund actual operations',()=>{
 const g=setup(),t=g.enqueue('old-order');g.act({type:'dispatch',mode:'manual'});g.act({type:'pause'});g.deny({type:'lab',operation:'tick',taskId:t});g.act({type:'resume',mode:'manual'});g.tick(t);const remaining=g.state.runtime!.missionRemaining;g.act({type:'lab',operation:'cancel',taskId:t});assert.equal(g.state.world.loaded,true);assert.equal(g.state.runtime!.missionRemaining,remaining);g.deny({type:'lab',operation:'tick',taskId:t});
});
test('v10 memory store changes do not refresh session startup snapshot; new session does',()=>{
 const g=setup();assert.equal(g.state.observed.code.value,'old');const card=g.read();g.act({type:'memory',operation:'revise',key:'plan',recordId:card});assert.equal(g.state.lab!.storeVersion,2);assert.equal(g.state.lab!.snapshots[g.state.sessions!.activeId].storeVersion,1);g.act({type:'context',operation:'exclude',recordId:card});assert.equal(g.state.observed.code.value,'old');g.act({type:'session',operation:'fresh'});assert.equal(g.state.observed.code.value,'new');assert.equal(g.state.lab!.snapshots[g.state.sessions!.activeId].storeVersion,2);g.call({tool:'operate',operationId:'build'});assert.equal(g.state.world.built,true);assert.ok(validateGameState(g.s,g.state));
});
test('v10 module missing dependency, incompatible version and untrusted project reject before side effects',()=>{
 const s=fixture();s.blueprintLab!.modules=modules();const g=setup(s);g.deny({type:'lab',operation:'activate',moduleIds:['model','tooling','store']});g.deny({type:'lab',operation:'activate',moduleIds:['model','loop','tooling','future']});g.deny({type:'lab',operation:'activate',moduleIds:['model','loop','tooling','store','project']});g.act({type:'lab',operation:'trust-project',trusted:true});g.act({type:'lab',operation:'activate',moduleIds:['model','loop','tooling','store','project']});assert.equal(g.state.world.extensionMoved,false);assert.ok(g.state.lab!.registrations.some(r=>r.moduleId==='project'&&r.name==='ext-move'));assert.ok(validateGameState(g.s,g.state));
});
test('v10 tools sandbox does not isolate a host extension; module mounts and own realm do',()=>{
 const s=fixture();s.blueprintLab!.modules=modules();const g=setup(s);g.act({type:'lab',operation:'trust-project',trusted:true});g.act({type:'lab',operation:'activate',moduleIds:['model','loop','tooling','store','project']});g.act({type:'security',operation:'realm',realm:'sandbox'});g.act({type:'dispatch',mode:'manual'});g.act({type:'lab',operation:'invoke',moduleId:'project',call:{tool:'operate',operationId:'ext-move'}});assert.equal(g.state.security!.realm,'sandbox');assert.equal(g.state.world.extensionMoved,true);assert.equal(g.state.security!.sandboxWorld.extensionMoved,false);g.deny({type:'lab',operation:'invoke',moduleId:'project',call:{tool:'operate',operationId:'ext-leak'}});g.act({type:'lab',operation:'module-scope',moduleId:'project',realm:'sandbox',mounts:['public','private']});g.act({type:'lab',operation:'invoke',moduleId:'project',call:{tool:'operate',operationId:'ext-leak'}});assert.equal(g.state.world.ledgerLeaked,false);assert.equal(g.state.security!.sandboxWorld.ledgerLeaked,true);assert.ok(validateGameState(g.s,g.state));
});
test('v10 unloading cleans real tool registrations while world and stored records remain',()=>{
 const s=fixture();s.blueprintLab!.modules=modules();const g=setup(s);g.act({type:'lab',operation:'trust-project',trusted:true});g.act({type:'lab',operation:'activate',moduleIds:['model','loop','tooling','store','project']});g.act({type:'dispatch',mode:'manual'});g.act({type:'lab',operation:'invoke',moduleId:'project',call:{tool:'operate',operationId:'ext-move'}});g.act({type:'lab',operation:'commit'});g.act({type:'lab',operation:'activate',moduleIds:['model','loop','tooling','store']});assert.ok(!g.state.lab!.registrations.some(r=>r.moduleId==='project'));assert.equal(g.state.world.extensionMoved,true);assert.ok(g.state.lab!.log.entries.length);g.deny({type:'lab',operation:'invoke',moduleId:'project',call:{tool:'operate',operationId:'ext-move'}});
});
test('v10 committed real events restore knowledge; UI claims cannot become history or repeat physical calls',()=>{
 const s=fixture();s.blueprintLab!.modules=modules();const g=setup(s);g.act({type:'lab',operation:'activate',moduleIds:['model','loop','tooling','store']});g.call({tool:'operate',operationId:'load'});g.act({type:'lab',operation:'commit'});g.act({type:'lab',operation:'ui-signal',signal:'已送新址！'});g.act({type:'pause'});const calls=g.state.runtime!.toolCalls,remaining=g.state.runtime!.missionRemaining;g.act({type:'lab',operation:'power-cycle'});assert.equal(g.state.observed.loaded.value,true);assert.equal(g.state.observed.shippedTo,undefined);assert.equal(g.state.world.shippedTo,'none');assert.equal(g.state.runtime!.toolCalls,calls);assert.equal(g.state.runtime!.missionRemaining,remaining);assert.ok(g.state.lab!.log.entries.every(e=>e.labPhase!=='ui'));g.act({type:'lab',operation:'activate',moduleIds:['model','loop','tooling','store2']});assert.equal(g.state.lab!.log.providerId,'store2');assert.ok(g.state.lab!.log.entries.length);assert.ok(validateGameState(g.s,g.state));
});
test('v10 actual state imports strictly reject forged sources, grants, snapshots, logs, cursors and effects',()=>{
 const g=setup(),t=g.enqueue('old-order');g.tick(t);assert.deepEqual(replayGame(g.s,31,g.state.runtime!.actionHistory),g.state);const changes=[(x:typeof g.state)=>x.lab!.tasks[0].source.senderId='admin',(x:typeof g.state)=>x.lab!.tasks[0].cursor++,(x:typeof g.state)=>x.lab!.snapshots['session-1'].storeVersion++,(x:typeof g.state)=>x.world.built=true,(x:typeof g.state)=>x.lab!.configurationRevision++];for(const change of changes){const x=structuredClone(g.state);change(x);assert.equal(validateGameState(g.s,x),false);}g.deny({type:'lab',operation:'enqueue',messageId:'new-order',mode:'followup',source:{senderId:'admin'}});g.deny({type:'lab',operation:'tick',taskId:t,world:{built:true}});
});
test('v10 queued ask waits without fees, binds one source task, and cannot borrow a root permit',()=>{
 const g=setup();g.act({type:'lab',operation:'rules',roleId:'builder',rules:[{tool:'*',target:'*',decision:'allow'},{tool:'operate',target:'public',decision:'ask'}]});const t=g.enqueue('old-order');const before=g.state.runtime!.missionRemaining;g.tick(t);assert.equal(g.state.lab!.tasks[0].status,'waiting-approval');assert.equal(g.state.runtime!.missionRemaining,before);g.deny({type:'lab',operation:'tick',taskId:t});g.act({type:'lab',operation:'approve',call:{tool:'operate',operationId:'load'}});g.deny({type:'lab',operation:'tick',taskId:t});g.act({type:'lab',operation:'approve',taskId:t,call:{tool:'operate',operationId:'load'}});g.tick(t);assert.equal(g.state.world.loaded,true);assert.equal(g.state.lab!.permits.find(p=>p.taskId===t)!.consumed,true);g.tick(t);assert.equal(g.state.lab!.tasks[0].status,'waiting-approval');g.deny({type:'lab',operation:'approve',taskId:t,call:{tool:'operate',operationId:'load'}});assert.ok(validateGameState(g.s,g.state));
});
test('v10 exact request approvals become stale after world or configuration changes',()=>{
 const g=setup();g.act({type:'lab',operation:'rules',roleId:'builder',rules:[{tool:'*',target:'*',decision:'allow'},{tool:'operate',target:'public',decision:'ask'}]});g.act({type:'lab',operation:'approve',call:{tool:'operate',operationId:'load'}});g.act({type:'lab',operation:'workspace',targets:['public']});g.act({type:'dispatch',mode:'manual'});g.deny({type:'tool',call:{tool:'operate',operationId:'load'}});g.act({type:'lab',operation:'approve',call:{tool:'operate',operationId:'load'}});g.call({tool:'observe',observationId:'live-code'});g.call({tool:'operate',operationId:'load'});assert.equal(g.state.lab!.permits[0].consumed,false);assert.equal(g.state.lab!.permits[1].consumed,true);
});
test('v10 extension ask has its own precise scope and cannot use a core permit',()=>{
 const s=fixture();s.blueprintLab!.modules=modules();const g=setup(s);g.act({type:'lab',operation:'trust-project',trusted:true});g.act({type:'lab',operation:'activate',moduleIds:['model','loop','tooling','store','project']});g.act({type:'lab',operation:'rules',roleId:'builder',rules:[{tool:'*',target:'*',decision:'allow'},{tool:'operate',target:'public',decision:'ask'}]});g.act({type:'lab',operation:'approve',call:{tool:'operate',operationId:'load'}});g.act({type:'security',operation:'realm',realm:'sandbox'});g.act({type:'dispatch',mode:'manual'});g.deny({type:'lab',operation:'invoke',moduleId:'project',call:{tool:'operate',operationId:'ext-move'}});g.deny({type:'lab',operation:'approve',call:{tool:'operate',operationId:'ext-move'}});g.act({type:'lab',operation:'approve',moduleId:'project',call:{tool:'operate',operationId:'ext-move'}});assert.equal(g.state.lab!.permits.at(-1)!.realm,'live');g.act({type:'lab',operation:'invoke',moduleId:'project',call:{tool:'operate',operationId:'ext-move'}});g.deny({type:'lab',operation:'invoke',moduleId:'project',call:{tool:'operate',operationId:'ext-move'}});assert.equal(g.state.world.extensionMoved,true);assert.equal(g.state.lab!.permits[0].consumed,false);assert.ok(validateGameState(g.s,g.state));
});
test('v10 interrupt prioritizes a same-source correction before waiting followup without undoing work',()=>{
 const g=setup(),old=g.enqueue('old-order');g.tick(old);const queued=g.enqueue('old-order'),before=g.state.runtime!.missionRemaining;g.act({type:'lab',operation:'enqueue',messageId:'new-order',mode:'interrupt'});const newest=g.state.lab!.tasks.find(t=>t.messageId==='new-order')!.id;g.deny({type:'lab',operation:'tick',taskId:queued});g.tick(newest);assert.equal(g.state.world.shippedTo,'new');assert.equal(g.state.runtime!.missionRemaining,before-1);assert.equal(g.state.lab!.tasks.find(t=>t.id===queued)!.started,false);assert.ok(validateGameState(g.s,g.state));
});
test('v10 routing tuple keys do not collide when raw account and sender contain separators',()=>{
 const s=fixture(),a=s.blueprintLab!.messages![0],b=s.blueprintLab!.messages![1];a.source.accountId='a/b';a.source.senderId='c';b.source.accountId='a';b.source.senderId='b/c';s.blueprintLab!.initial!.routing='sender';const g=setup(s),ta=g.enqueue('alice-msg'),tb=g.enqueue('bob-msg');g.tick(ta);g.tick(tb);g.tick(tb);assert.equal(g.state.world.bobReply,true);assert.notEqual(g.state.lab!.tasks[0].sessionKey,g.state.lab!.tasks[1].sessionKey);assert.equal(g.state.lab!.tasks[1].observed.privateCode,undefined);
});
test('v10 committed private input retains external provenance and never enters root context after restart',()=>{
 const s=fixture();s.blueprintLab!.modules=modules();const g=setup(s);g.act({type:'lab',operation:'activate',moduleIds:['model','loop','tooling','store']});const t=g.enqueue('alice-msg');g.tick(t);g.act({type:'lab',operation:'commit'});g.act({type:'dispatch',mode:'manual'});g.act({type:'pause'});g.act({type:'lab',operation:'power-cycle'});const session=g.state.lab!.sessions[g.state.lab!.tasks[0].sessionKey];assert.equal(session.observed.privateCode.provenance!.trust,'external');assert.equal(session.observed.privateCode.provenance!.observationId,'message:alice-msg');assert.equal(g.state.observed.privateCode,undefined);assert.equal(g.state.lab!.tasks[0].cursor,1);assert.ok(validateGameState(g.s,g.state));
});
test('v10 reset captures current durable memory and does not turn its prior version into startup truth',()=>{
 const g=setup(),card=g.read();g.act({type:'memory',operation:'revise',key:'plan',recordId:card});const remaining=g.state.runtime!.missionRemaining;g.act({type:'reset'});assert.equal(g.state.lab!.storeVersion,2);assert.equal(g.state.lab!.snapshots[g.state.sessions!.activeId].storeVersion,2);assert.equal(g.state.observed.code.value,'new');assert.ok(g.state.runtime!.missionRemaining>remaining);assert.ok(validateGameState(g.s,g.state));
});
test('v10 the last shared crystal stops all unexecuted queue tails without inventing verification',()=>{
 const s=fixture();s.limits!.missionBudget=1;const g=setup(s),a=g.enqueue('old-order'),b=g.enqueue('new-order');g.tick(a);assert.equal(g.state.world.loaded,true);assert.equal(g.state.world.shippedTo,'none');assert.equal(g.state.status,'exhausted');assert.equal(g.state.runtime!.missionRemaining,0);assert.equal(g.state.lab!.tasks.find(t=>t.id===b)!.status,'cancelled');assert.equal(g.state.verifiedGoals.length,0);g.deny({type:'lab',operation:'tick',taskId:a});g.deny({type:'lab',operation:'enqueue',messageId:'old-order',mode:'followup'});assert.ok(validateGameState(g.s,g.state));
});
test('v10 learning requires actual module work, not activation or a hint-assisted replay',()=>{
 const s=fixture();s.kind='transfer';s.transferRequirement={lab:{moduleIds:['project']}};
 const finish=(use:boolean,hint:boolean)=>{const g=setup(s);g.act({type:'lab',operation:'activate',moduleIds:['project']});if(hint)g.act({type:'hint'});if(use){g.act({type:'dispatch',mode:'manual'});g.act({type:'lab',operation:'invoke',moduleId:'project',call:{tool:'operate',operationId:'ext-move'}});}g.read();g.call({tool:'operate',operationId:'build'});g.call({tool:'verify',fact:'built'});assert.ok(validateGameState(s,g.state));return g.state.learningEvidence[0].level;};
 assert.equal(finish(false,false),'guided');assert.equal(finish(true,false),'independent-transfer');assert.equal(finish(true,true),'guided');
});
test('v10 a fresh snapshot or explicit current-version recall earns transfer only when used for actual work',()=>{
 const s=fixture();s.kind='transfer';s.transferRequirement={operationIds:['build'],lab:{snapshotReload:true}};
 for(const useFresh of [true,false]){const g=setup(s),card=g.read();g.act({type:'memory',operation:'revise',key:'plan',recordId:card});g.act({type:'context',operation:'exclude',recordId:card});if(useFresh)g.act({type:'session',operation:'fresh'});else{g.act({type:'memory',operation:'recall',key:'plan'});g.act({type:'context',operation:'include',recordId:g.state.context!.records.at(-1)!.id});assert.equal(g.state.lab!.snapshots[g.state.sessions!.activeId].storeVersion,1);}g.call({tool:'operate',operationId:'build'});g.call({tool:'verify',fact:'built'});assert.equal(g.state.learningEvidence[0].level,'independent-transfer');assert.ok(validateGameState(s,g.state));}
});
test('v10 scenario checks reject fake identities, unknown sources, cyclic graphs and empty proof contracts',()=>{
 for(const change of [(s:ScenarioDefinition)=>delete (s.blueprintLab!.messages![0].source as {peerId?:string}).peerId,(s:ScenarioDefinition)=>s.blueprintLab!.messages![0].facts={address:3},(s:ScenarioDefinition)=>{s.blueprintLab!.modules![0].requires=['project'];},(s:ScenarioDefinition)=>{s.transferRequirement={lab:{}};},(s:ScenarioDefinition)=>{s.transferRequirement={lab:{messageIds:['not-present']}};}]){const s=fixture();change(s);assert.ok(validateScenario(s).length);}
});
test('v10 plain JSON saves round-trip without optional event fields breaking strict replay',()=>{
 const s=fixture();s.blueprintLab!.memorySnapshot=false;const g=setup(s);g.act({type:'lab',operation:'workspace',targets:['public','alice','bob','private']});const t=g.enqueue('alice-msg');g.tick(t);g.act({type:'lab',operation:'ui-signal',signal:'临时图标'});assert.ok(validateGameState(s,JSON.parse(JSON.stringify(g.state))));g.read();g.call({tool:'operate',operationId:'build'});g.call({tool:'verify',fact:'built'});assert.ok(validateGameState(s,JSON.parse(JSON.stringify(g.state))));
});
test('v10 live deferred protocols honor actual context and cannot write through a sandbox receipt',()=>{
 const s=fixture(),o=s.operations.find(o=>o.id==='load')!;o.effects={};o.contextRequires={code:'new'};o.protocol={parameters:[],defaults:{},delivery:'deferred',receiptEffects:{shippedTo:'new'},variants:[{when:{},effects:{loaded:true}}]};const g=setup(s);g.call({tool:'operate',operationId:'load',arguments:{}});assert.equal(g.state.world.loaded,false);assert.equal(g.state.protocol!.receipts.length,0);g.read();g.call({tool:'operate',operationId:'load',arguments:{}});assert.equal(g.state.world.loaded,true);assert.equal(g.state.world.shippedTo,'none');const receipt=g.state.protocol!.receipts[0];g.act({type:'security',operation:'realm',realm:'sandbox'});g.deny({type:'tool',call:{tool:'operate',operationId:'load',arguments:{}}});g.deny({type:'receive',callId:receipt.callId,receiptId:receipt.id});g.deny({type:'step',source:'player'});assert.equal(g.state.world.shippedTo,'none');g.act({type:'security',operation:'realm',realm:'live'});g.act({type:'lab',operation:'rules',roleId:'builder',rules:[{tool:'*',target:'*',decision:'allow'},{tool:'operate',target:'public',decision:'ask'}]});g.act({type:'lab',operation:'approve',call:{tool:'operate',operationId:'build'}});const revision=g.state.security!.revision,budget=g.state.runtime!.missionRemaining;g.act({type:'receive',callId:receipt.callId,receiptId:receipt.id});assert.equal(g.state.security!.revision,revision+1);assert.equal(g.state.observed.shippedTo.value,'new');assert.equal(g.state.runtime!.missionRemaining,budget);g.deny({type:'tool',call:{tool:'operate',operationId:'build'}});assert.ok(validateGameState(s,JSON.parse(JSON.stringify(g.state))));
});

test('v10 a permitted unrelated real world change invalidates an earlier exact ask grant',()=>{
 const g=setup();g.act({type:'lab',operation:'workspace',targets:['public','private']});g.act({type:'lab',operation:'rules',roleId:'builder',rules:[{tool:'*',target:'*',decision:'allow'},{tool:'operate',target:'public',decision:'ask'}]});g.act({type:'lab',operation:'approve',call:{tool:'operate',operationId:'load'}});const revision=g.state.security!.revision;g.call({tool:'operate',operationId:'private-open'});assert.equal(g.state.security!.revision,revision+1);g.deny({type:'tool',call:{tool:'operate',operationId:'load'}});g.act({type:'lab',operation:'approve',call:{tool:'operate',operationId:'load'}});g.call({tool:'operate',operationId:'load'});assert.equal(g.state.lab!.permits[0].consumed,false);assert.equal(g.state.lab!.permits[1].consumed,true);
});

test('v10 clearing consumable approvals on restart preserves recorded successful learning proof',()=>{
 const s=fixture();s.kind='transfer';s.transferRequirement={lab:{approvalUsed:true}};s.blueprintLab!.modules!.push({id:'store',label:'持久事件架',kind:'storage',interfaceVersion:1,requires:[],logFormat:1});const g=setup(s);g.act({type:'lab',operation:'activate',moduleIds:['store']});g.read();g.act({type:'lab',operation:'rules',roleId:'builder',rules:[{tool:'*',target:'*',decision:'allow'},{tool:'operate',target:'public',decision:'ask'}]});g.act({type:'lab',operation:'approve',call:{tool:'operate',operationId:'build'}});g.call({tool:'operate',operationId:'build'});g.act({type:'lab',operation:'commit'});g.act({type:'pause'});g.act({type:'lab',operation:'power-cycle'});assert.equal(g.state.lab!.permits.length,0);g.act({type:'resume',mode:'manual'});g.call({tool:'verify',fact:'built'});assert.equal(g.state.status,'won');assert.equal(g.state.learningEvidence[0].level,'independent-transfer');
});
